export const mobileNavData = {
  voiceData: [
    "Glo Berekete Tarrif Plan",
    "Glo Yakata",
    "Glo 11k/s Prepaid Plan",
    "Glo Jolliffic8",
    "Infinito",
    "G-BAM",
    "Easy Share",
    "international Calling (IDD)",
    "IDD Slasher",
    "Call Services",
  ],

  dataPackages: [
    "Data Plans",
    "Upgrade 3G to 4G offer",
    "Glo Data Calculator",
    "Data Sharing",
    "Data Gifting",
    "Glo CAMPUS Data BOOSTER",
    "Glo WIFI",
    "Glo HSI Portal",
    "BlackBerry Plans",
    "Glo Mega Deals/Offers",
  ],

  devices: ["Apple", "Huawei", "Imose", "Infinix", "Nokia", "SamSung", "Tecno"],

  roaming: ["Prepaid", "Postpaid", "Hajj Offer", "Data", "Roaming FAQs"],
  specialPacks: [
    "Glo Super Value Pack",
    "Glo Oga Sim",
    "Glo 4X",
    "Jolof Recharge",
    "IDD Packs",
    "Glo BilGy Packs",
    "Glo Flexi",
  ],
  corporatePackages: [
    "Postpaid Smart Plans",
    "infinitizer",
    "Biz Maximizer",
    "Biz Optimizer",
    "Biz Vantage",
    "Toll Free Service",
  ],
  enterpriseSolutions: [
    "Glo School Data Packs",
    "Glo Sponsored Data Services",
    "Glo Smart Learning Suite",
    "4G-LTE Enterprise Dedicated Bandwidth Service",
    "Broadband",
    "Fixed Lines",
    "Network Infrastructure",
    "Wholesale & Global",
  ],
  gateway: ["Mobile Solutions", "Wholesale Services"],
  publicSector: [
    "Public Call Offices",
    "Rural Telephony",
    "SME",
    "Free Access Programme",
  ],
  lifestyle: [
    "Glo Cafe - Multi Channel Self Care App",
    "Gaming Portal (Playing)",
    "Borrow Me Data",
    "Dorrow Me Credit",
    "Caller Tunes",
  ],
  entertainment: ["Glo GameBox"],
  storage: ["Glo Cloud"],
  education: ["Busuu"],
};
