import React from "react";
import SharedHeader from "../SharedContent/SharedHeader";
import "./eTopUp.css";
import eTopUpImg from "../../../assets/1040x300-e-Top-Up.gif";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { pageEntryVariant, variantProps } from "../../variants/page";
import useDocumentTitle from "../UseTitle";
const ETopUp = () => {
  useDocumentTitle("E-Top Up");
  return (
    <motion.section
      className="e-topUp"
      variants={pageEntryVariant}
      {...variantProps}
    >
      <SharedHeader heading="E-Top-Up" />
      <section className="shared__contentContainer">
        <section className="e-topUp__imgContainer">
          <img src={eTopUpImg} alt="top up" />
        </section>
        <section className="e-topUp__details">
          <p>
            <strong>eTop-Up </strong> is a dynamic and convenient electronic
            recharge alternative for topping up subscribers without scratching a
            card. It is a fast and readily accessible means of recharging mobile
            accounts that is why the Glo eTop-Up is called{" "}
            <em>‘Glo sharpsharp’</em>. Subscribers can buy flexible
            denominations between N50-N500,000 in one transaction at an
            incremental of N1; N800,000 in one day. Thus, the Electronic
            Recharge System enables the true experience of{" "}
            <em>‘anytime, anywhere, any value top-up’</em>
          </p>
          <div className="e-topUp__more">
            <h2>
              Click here to <Link to="/ng/recharge-now">RECHARGE NOW</Link>
            </h2>
            <p>You can also enjoy the eTop-Up on the following channels:</p>
            <article className="detail">
              <strong>Data Recharge:</strong> Replenish your data directly by
              via eTop-Up without first loading airtime and converting to Data.
              Simply pick the data plan, pay the value and you are loaded.
            </article>
            <article className="detail">
              <strong>Voucher on Demand:</strong> Buy eTop-Up from a print
              enabled channel eg POS or ATM without restriction to value, then
              load the pin by dialing *203*3*pin
            </article>
            <article className="detail">
              <strong>Anonymous ID: </strong> This is a peculiar smart code
              personally generated by dialing *203*1#. The code is attached to
              your MSISDN and if you load airtime on the code, your Glo line
              gets the credit. This offers you anonymity and privacy as you are
              protected from giving out their MSISDN number before loading
              airtime as calls to the smartcode will not be connected
            </article>
          </div>
        </section>
        <div className="e-topUp__dealer">
          <p>
            To become an <strong>eTop-Up/Web Dealer</strong>, please email:
            etopuptradesupport@gloworld.com
          </p>
          <p>
            <Link to="/ng/frequent-questions">Click here</Link> for Frequently
            Asked Questions
          </p>
        </div>
        <ul className="e-topUp__nav">
          <li>
            <Link to="/ng/e-top-up/e-top-up-15-offer">E Top-Up 15% Offer</Link>
          </li>
          <li>
            <Link to="/ng/e-top-up/glo-simple-recharge">
              Glo Simple Recharge
            </Link>
          </li>
          <li>
            <Link to="/ng/e-top-up/glo-amebo">Glo Amebo</Link>
          </li>
        </ul>
      </section>
    </motion.section>
  );
};

export default ETopUp;
